# Generated by Django 5.0.1 on 2024-03-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CakeBox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakevariant',
            name='shape',
            field=models.CharField(choices=[('Round', 'Round'), ('Square', 'Square'), ('Heart', 'Heart'), ('Custom', 'Custom')], default='Round', max_length=10),
        ),
    ]
