# Generated by Django 5.0.1 on 2024-03-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CakeBox', '0002_cakevariant_shape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='flavour_object',
        ),
        migrations.AddField(
            model_name='cake',
            name='flavour_object',
            field=models.ManyToManyField(to='CakeBox.flavour'),
        ),
    ]
