# Generated by Django 5.0.1 on 2024-03-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CakeBox', '0003_remove_cake_flavour_object_cake_flavour_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cakevariant',
            name='base_price',
        ),
        migrations.AddField(
            model_name='cake',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
