# Generated by Django 5.0.1 on 2024-03-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CakeBox', '0004_remove_cakevariant_base_price_cake_base_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='base_price',
        ),
        migrations.AddField(
            model_name='cakevariant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
