# Generated by Django 5.0.1 on 2024-03-25 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CakeBox', '0005_remove_cake_base_price_cakevariant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='flavour_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CakeBox.flavour'),
        ),
        migrations.AddField(
            model_name='basketitem',
            name='occasion_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CakeBox.occasion'),
        ),
    ]
